# Generated by Django 5.0.8 on 2024-08-07 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spoiledpotato', '0002_movie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='birthday',
            field=models.DateField(),
        ),
    ]
