# Generated by Django 5.0.8 on 2024-08-07 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spoiledpotato', '0003_alter_actor_birthday'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='actor',
        ),
        migrations.AddField(
            model_name='movie',
            name='actor',
            field=models.ManyToManyField(related_name='movies', to='spoiledpotato.actor'),
        ),
    ]
