# Generated by Django 5.0.8 on 2024-08-08 03:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spoiledpotato', '0004_remove_movie_actor_movie_actor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='actor',
            new_name='actors',
        ),
    ]
